### ISSUE TITLE
Wands not doing anything

### ISSUE THREAD

**Issue by arrrrik** [InfinityRaider/ElementalInvocations#9]
Basically what it says- current build (last commit was cd61be3) has the wands just things you wave around. No charges are generated, no effects happen when you cast- nothing. Tested myself and had a friend test- no luck on either end.

Using forge 2045 (also tried 2046 just for kicks). Here's a client log http://pastebin.com/wfZRLrTs, here's a FML log http://pastebin.com/vmqz6U98

**Comment by InfinityRaider** [comment]
You have to set your magic affinity first by consuming an orb or using the debugger
